name: waiter_app
description: Food Bank Waiter App


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^0.13.4
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^9.2.0
  flutter_secure_storage: ^5.0.2
  email_auth: ^1.0.0
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.3
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: "launcher_icon"
  ios: true


flutter_native_splash:
  color: "#EE1D48"
  image: assets/images/splash_logo.png


flutter:


  uses-material-design: true

  assets:
    - assets/images/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

